openapi: 3.0.0
info:
  title: Esteban Basketball Team API
  version: 1.0.0
  description: 농구 팀 관리 시스템 API 문서

servers:
  - url: http://localhost:3000/api/v1/

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /user/admin-login:
    post:
      tags: [user]
      summary: 관리자 계정 로그인
      description: 관리자 계정으로 로그인합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 관리자 계정 로그인 성공
  /user/logout:
    get:
      tags: [user]
      summary: 로그아웃
      description: 로그아웃 합니다.
      parameters:
        - in: cookie
          name: access_token
          required: true
          schema:
            type: string
      responses:
        200:
          description: 로그아웃 성공

  /team/members:
    get:
      tags: [team]
      summary: 팀 회원 전체 조회
      description: 팀에 속한 모든 회원의 정보를 조회합니다.
      security:
        - BearerAuth: []
      responses:
        200:
          description: 회원 목록 조회 성공
